Repository wecode-bootcamp-korea/29-1st-Wesop-frontend, pull requests merged in 2022-02, with the labels that each got.

#14 [29기 박겸영] footer 구현
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterSection/FooterSection.js
  src/components/Footer/footerData.js
Labels: Status: 리뷰 요청

#16 [공통] Modify: config.js
  src/components/Carousel/Carousel.js
  src/config.js
Labels: Status: 리뷰 요청

#17 [29기 박겸영] 메인 페이지 refactoring
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#9 [29기 박겸영] 로그인 및 회원가입 구현
  src/components/LoginModal/ForgotPasswordForm/ForgotPasswordForm.js
  src/components/LoginModal/LoginForm/LoginForm.js
  src/components/LoginModal/LoginLayout/FormText/FormText.js
  src/components/LoginModal/LoginLayout/FormText/FormText.scss
  src/components/LoginModal/LoginLayout/LoginLayout.js
  src/components/LoginModal/LoginLayout/LoginLayout.scss
  src/components/LoginModal/LoginModal.js
  src/components/LoginModal/LoginModal.scss
  src/components/LoginModal/SigninForm/SigninForm.js
  src/components/LoginModal/SignupForm/SignupForm.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/styles/common.scss
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#2 [29기 정지민] Nav 진행 중
  public/data/CategoryList.json
  public/data/NavData.json
  public/data/data.json
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavModal/CategoryList.js
  src/components/Nav/NavModal/CategoryLists.js
  src/components/Nav/NavModal/CategoryLists.scss
  src/components/Nav/NavModal/CategoryModal.js
  src/components/Nav/NavModal/CategoryModal.scss
  src/components/Nav/NavModal/CategoryModalLayout.js
  src/components/Nav/NavModal/MainCategoryList.js
Labels: Status: Accepted

#20 [29기 박겸영] 메인 페이지 수정
  src/components/Carousel/Carousel.js
  src/components/Carousel/CarouselItem/CarouselItem.scss
  src/pages/Main/Main.js
Labels: Status: Accepted

#21 [29기 박겸영] footer 리팩토링
  src/components/Footer/Footer.scss
Labels: Status: Accepted

#22 [공통] config.js 수정
  src/config.js
Labels: Status: Accepted

#25 [29기 박겸영] Add: 로그인 모달 Nav에 추가
  src/components/Nav/Nav.js
  src/pages/Main/Main.js
Labels: Status: Accepted

#26 [공통] Add: favicon
  public/favicon.ico
  public/images/wesop_favicon_img.png
  public/index.html
Labels: Status: Accepted

#27 [29기 박겸영] 메인 페이지 수정
  src/pages/Main/Home/Home.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: Accepted

#24 [29기 정지민] Nav.scss 수정
  public/data/CategoryList.json
  public/data/NavData.json
  src/components/Nav/Nav.scss
  src/components/Nav/NavModal/CategoryList.js
  src/components/Nav/NavModal/CategoryModalLayout.js
  src/components/Nav/NavModal/MainCategoryList.js
  src/config.js
Labels: Status: Accepted

#28 [29기 정지민] Nav Refactoring
  src/components/Nav/Nav.js
  src/components/Nav/NavModal/CategoryLists.js
  src/components/Nav/NavModal/CategoryLists.scss
  src/components/Nav/NavModal/CategoryModal.js
  src/components/Nav/NavModal/MainCategoryList.js
Labels: Status: Accepted

#31 [29기 박겸영] 로그인 함수 수정
  src/components/LoginModal/LoginModal.js
  src/components/LoginModal/LoginModal.scss
  src/components/LoginModal/SigninForm/SigninForm.js
Labels: Status: Accepted

#11 [29기 박무선] 상세페이지 컴포넌트화 및 기능 구현중
  public/data/data.json
  src/pages/ProductsDetail/CartModal/CartModal.js
  src/pages/ProductsDetail/CartModal/CartModal.scss
  src/pages/ProductsDetail/INFO_DATA.js
  src/pages/ProductsDetail/IngredientsModal/IngredientsModal.js
  src/pages/ProductsDetail/IngredientsModal/IngredientsModal.scss
  src/pages/ProductsDetail/ProductsDetail.js
  src/pages/ProductsDetail/ProductsDetail.scss
  src/pages/ProductsDetail/ProductsHeader/ProductsHeader.js
  src/pages/ProductsDetail/ProductsHeader/ProductsHeader.scss
  src/pages/ProductsDetail/ProductsMain/ProductsMain.js
  src/pages/ProductsDetail/ProductsMain/ProductsMain.scss
  src/pages/ProductsDetail/ProductsSlider/ProductsSlider.js
  src/pages/ProductsDetail/ProductsSlider/ProductsSlider.scss
Labels: Status: Accepted

#30 [29기 김지윤] 제품 카테고리 페이지 라디오 버튼 삭제
  src/pages/ProductsList/SubcatProduct/SubcatProduct.js
Labels: Status: 수정 요청

#7 [29기 정지민] Cart 구현 중
  public/data/CartData.json
  public/data/data.json
  src/components/Nav/Cart/Cart.js
  src/components/Nav/Cart/CartModal.js
  src/components/Nav/Cart/CartModal.scss
  src/components/Nav/Cart/CartProduct.js
  src/components/Nav/Cart/Option.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/Main/Main.js
  src/pages/ProductsList/SubcatProduct/SubcatProduct.js
Labels: Status: 추가 기능 구현중
